DocWorks for wix-stores-backend - 60 changes detected, but 40 issue detected changes: Service wix-stores-backend operation createProduct.examples[0] has changed body Service wix-stores-backend has a new operation createOrder Service wix-stores-backend message Address member firstName was removed Service wix-stores-backend message Address member lastName was removed Service wix-stores-backend message Address member email was removed Service wix-stores-backend message Address member phone was removed Service wix-stores-backend message Address member address was removed Service wix-stores-backend message Address has a new member formatted Service wix-stores-backend message Address has a new member city Service wix-stores-backend message Address has a new member country Service wix-stores-backend message Address has a new member addressLine Service wix-stores-backend message Address has a new member addressLine2 Service wix-stores-backend message Address has a new member streetAddress Service wix-stores-backend message Address has a new member postalCode Service wix-stores-backend message Address has a new member subdivision Service wix-stores-backend message Address has changed summary Service wix-stores-backend message Address.examples has 2 examples removed Service wix-stores-backend message Cart member billingAddress has changed type Service wix-stores-backend message Cart member lineItems has changed type Service wix-stores-backend message LineItem was removed Service wix-stores-backend message MediaItem member title was removed Service wix-stores-backend message MediaItem member description was removed Service wix-stores-backend message MediaItem member type has changed doc Service wix-stores-backend message MediaItem member src has changed doc Service wix-stores-backend message MediaItem member thumbnail was removed Service wix-stores-backend message MediaItem has a new member altText Service wix-stores-backend message MediaItem has a new member externalImageUrl Service wix-stores-backend message MediaItem has changed summary Service wix-stores-backend message MediaItem.examples has 1 examples removed Service wix-stores-backend message Product.examples[0] has changed body Service wix-stores-backend message ShippingInfo was removed Service wix-stores-backend has a new message CartAddress Service wix-stores-backend has a new message CartShippingInfo Service wix-stores-backend has a new message CartLineItem Service wix-stores-backend has a new message Order Service wix-stores-backend has a new message OrderInfo Service wix-stores-backend has a new message CreateOrderBuyerInfo Service wix-stores-backend has a new message Activities Service wix-stores-backend has a new message StreetAddress Service wix-stores-backend has a new message VatId Service wix-stores-backend has a new message ChannelInfo Service wix-stores-backend has a new message EnteredBy Service wix-stores-backend has a new message CreateOrderBillingInfo Service wix-stores-backend has a new message BillingInfo Service wix-stores-backend has a new message OrderShippingInfo Service wix-stores-backend has a new message ShipmentPriceData Service wix-stores-backend has a new message LineItemPriceData Service wix-stores-backend has a new message CreateOrderLineItemPriceData Service wix-stores-backend has a new message ShipmentDetails Service wix-stores-backend has a new message PickupDetails Service wix-stores-backend has a new message CreateOrderMediaItem Service wix-stores-backend has a new message OrderLineItem Service wix-stores-backend has a new message CreateOrderLineItem Service wix-stores-backend has a new message Totals Service wix-stores-backend has a new message CreateOrderTotals Service wix-stores-backend has a new message CustomField Service wix-stores-backend has a new message LineItems Service wix-stores-backend has a new message TrackingInfo Service wix-stores-backend has a new message Fulfillment Service wix-stores-backend has a new message Discount
issues:
Message CartCompletedEvent has an unknown property type wix-stores-backend.ShippingInfo (events.js (183))
Message ProductCreatedEvent has an unknown property type $w.Gallery.VideoItem (events.js (216))
Message Cart has an unknown property type wix-stores-backend.ShippingInfo (carts.js (1))
Message AppliedCoupon is defined two or more times (carts.js (32), orders.js (478))
Message BuyerInfo is defined two or more times (carts.js (52), orders.js (99))
Message Option is defined two or more times (carts.js (120), orders.js (313))
Message CustomTextField is defined two or more times (carts.js (131), orders.js (341))
Message MediaItem is defined two or more times (orders.js (321), products.js (66))
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 20
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 66
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 92
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 99
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 119
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 148
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 156
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 170
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 178
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 198
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 215
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 231
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 249
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 260
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 268
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 277
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 285
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 301
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 313
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 321
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 332
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 341
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 349
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 384
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 418
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 431
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 442
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 451
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 459
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 468
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 478
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 487