DocWorks for wix-test-jdoc - 1 change detected, but 1 issue detected changes: Service top-level-namespace was removed
issues:
ERROR: Unable to parse /Users/harelmo/dev/jsdoc-playground/corvid-docs/main.js: Unexpected character '@'