DocWorks for wix-stores-backend - 6 changes detected, but 38 issue detected changes: Service wix-stores-backend message Order member buyerInfo has changed type Service wix-stores-backend message Order member fulfillmentStatus has changed doc Service wix-stores-backend message Order member paymentStatus has changed doc Service wix-stores-backend message Order.examples has 1 new examples Service wix-stores-backend message OrderInfo member paymentStatus has changed doc Service wix-stores-backend has a new message OrderBuyerInfo
issues:
Message CartCompletedEvent has an unknown property type wix-stores-backend.ShippingInfo (events.js (183))
Message ProductCreatedEvent has an unknown property type $w.Gallery.VideoItem (events.js (216))
Message Cart has an unknown property type wix-stores-backend.ShippingInfo (carts.js (1))
Message AppliedCoupon is defined two or more times (carts.js (32), orders.js (481))
Message Option is defined two or more times (carts.js (120), orders.js (316))
Message CustomTextField is defined two or more times (carts.js (131), orders.js (344))
Message MediaItem is defined two or more times (orders.js (324), products.js (66))
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 68
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 95
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 102
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 122
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 151
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 159
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 173
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 181
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 201
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 218
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 234
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 252
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 263
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 271
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 280
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 288
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 304
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 316
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 324
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 335
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 344
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 352
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 387
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 421
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 434
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 445
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 454
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 462
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 471
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 481
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrderFull.es6' not found. File: orders.js line: 490